# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: wasm-golang tests pipeline

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: golang:1.16-alpine

    steps:
      - name: Install Dependencies
        run: apk add --no-cache git gcc g++ curl

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint project
        run: |
          go get -u golang.org/x/lint/golint
          golint -set_exit_status ./...
